name: 🚀 Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - package*.json
      - docs/changelog.md
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # [setup] authenticate with the cicd app to get proper credentials for pushing to the repo later.
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v2.1.1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      # [setup] checkout the repo.
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      # [setup] setup node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x
      # [setup] configure git for later changelog generation, commit, and the finalpush.
      - name: configure git
        run: |
          git config --global user.name "mateothegreat[bot]"
          git config --global user.email "mateothegreat[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git
      # [build] install dependencies first.
      - name: install
        run: npm install
      # [build] build the package which outputs to the dist/ directory.
      - name: build
        run: npm run build
      # [version] bump the version.asdf
      - name: npm version
        id: version
        run: |
          version=$(npm version patch --no-git-tag-version --json | sed 's/^v//' || {
            echo "npm version patch failed, git is dirty"
            exit 1
          })
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "version is now: $version"
      # [version] generate the new changelog.
      - name: generate changelog
        uses: orhun/git-cliff-action@98c93442bb05a455a77bee982867857ae748eeea
        id: git-cliff
        with:
          config: ./docs/cliff.toml
          args: --strip header --latest --tag ${{ steps.version.outputs.version }}
        env:
          OUTPUT: docs/changelog.md
      # [version] commit the changelog and package.json.
      - name: commit
        run: |
          git add docs/changelog.md package.json
          git commit -am "chore(release): update changelog and bumping package.json"
          git tag -l
          git push origin HEAD:main --follow-tags
      # [publish] prepare to publish by setting up credentials.
      - name: write to .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      # [publish] release publicly only if the build was successful above.
      - name: publish
        run: npm publish
      # [publish] create a github release.
      - name: create github release
        uses: softprops/action-gh-release@v2.3.2
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          tag_name: ${{ steps.version.outputs.version }}
  notify:
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@ad5235de713df3ef38022185499b02ffe93b7efe
        with:
          status: ${{ needs.build.result }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
